"""Update column lengths in User model

Revision ID: 8413ce952c52
Revises: 74d1b31bcf73
Create Date: 2024-08-05 23:05:13.794010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8413ce952c52'
down_revision = '74d1b31bcf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_follower_followed', ['follower_id', 'followed_id'])

    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_post', ['user_id', 'post_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('profile_pic',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_post', type_='unique')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('uix_follower_followed', type_='unique')

    # ### end Alembic commands ###
